# Generated by Django 3.2.2 on 2021-05-25 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TesteModel',
        ),
    ]
