# Generated by Django 3.2.2 on 2021-05-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_moviemodels_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodels',
            name='genres',
            field=models.ManyToManyField(to='movies.GenreModels'),
        ),
    ]
