# Generated by Django 3.2.2 on 2021-06-07 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20210607_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodels',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.moviemodels'),
            preserve_default=False,
        ),
    ]
