# Generated by Django 3.2.2 on 2021-06-07 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_commentmodels_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodels',
            old_name='comment_user',
            new_name='user',
        ),
    ]
